### ISSUE TITLE
Issues with framelines interpretation in R

### ISSUE THREAD

**Issue by Mette-Jill** [detsutut/chroma#2] opened 2020-03-11 09:08 UTC
In CSV to Data frame (first step to implement frames in R)
-> unclear where to place own csv file
-> function 'groupframes' does not store data (cannot find .session$ in function)
-> at ggplot(plot2, plotwidgets), it says that 'plotwidgets' does not exist.

**Comment by Mette-Jill** [comment] 2020-03-11 09:09
ready-to-go database 'miyazaki' cannot be found in ChromaR package?

**Comment by Mette-Jill** [comment] 2020-03-11 10:43
With ChromaR: implementing own data with ChromaR::getFrames() -> the function choose.files(..) in does not exist; should this be file.choose()?

**Comment by detsutut** [comment] 2020-03-14 17:13
> ready-to-go database 'miyazaki' cannot be found in ChromaR package?

Git was mistakenly ignoring the data folder. The 'miyazaki' dataset should be available now.

**Comment by detsutut** [comment] 2020-03-14 17:23
> With ChromaR: implementing own data with ChromaR::getFrames() -> the function choose.files(..) in does not exist; should this be file.choose()?

choose.files() and file.choose() are two different functions, both valid. The first one is Windows-only though, so this could be the issu if you're using a different OS.

choose.files() will be replaced in the next update.

**Comment by detsutut** [comment] 2020-03-14 17:24
> In CSV to Data frame (first step to implement frames in R)
> -> unclear where to place own csv file
> -> function 'groupframes' does not store data (cannot find .session$ in function)
> -> at ggplot(plot2, plotwidgets), it says that 'plotwidgets' does not exist.

Can you provide a reproducible example for this?

**Comment by Mette-Jill** [comment] 2020-03-19 13:31
When following the code on towardsdatascience, R still gives the error that 'miyazaki' is not an exported object from 'namespace:chromaR'

**Comment by Mette-Jill** [comment] 2020-03-19 13:39
When i re-write the getFrames() function to use file.choose everything works fine!

**Comment by Mette-Jill** [comment] 2020-03-19 13:48
When I follow the code with my own csv.file (which I implemented by adapting the getFrames() to use file.choose instead of choose.files), when I run the line
framelines = lapply(movies,function(movie){groupframes(movie,seconds = 0.05)})
I get an error saying that in the groupframe function: function(frames,seconds=NULL,fps=.session$fps) -> object '.session' is not found.

**Comment by detsutut** [comment] 2020-03-20 12:47
> When following the code on towardsdatascience, R still gives the error that 'miyazaki' is not an exported object from 'namespace:chromaR'

This should have been solved with [this commit](https://github.com/detsutut/chroma/commit/7320a0f0adbcf14332828cb67e32343659dc7307)

Do you still get an error after running `install_github("detsutut/chroma", subdir="chromaR")` again?
If so, can you provide the full error message here?

**Comment by detsutut** [comment] 2020-03-20 12:52
> When I follow the code with my own csv.file (which I implemented by adapting the getFrames() to use file.choose instead of choose.files), when I run the line
> framelines = lapply(movies,function(movie){groupframes(movie,seconds = 0.05)})
> I get an error saying that in the groupframe function: function(frames,seconds=NULL,fps=.session$fps) -> object '.session' is not found.

Looks like the chromaRenv couldn't be reached. Can you please try `function(frames,seconds=NULL,fps=24) ` ?

**Comment by Mette-Jill** [comment] 2020-03-20 13:45
I updated it again and the miyazaki file works like a charm! Only the getFrames() function still works with choose.files() which I dont have on my mac.

**Comment by Mette-Jill** [comment] 2020-03-20 14:25
I forgot that I also edited the chromaRenv part in the getFrames() function, because I got the same error there in the line: 
attr(frames, "duration") <- round(max(frames$frameId)/chromaRenv$fps)
I guess its the same issue?

**Comment by detsutut** [comment] 2020-03-20 14:53
I created two different threads for your issues. 
If you don't have any other problem with the miyazaki default dataset in the chromaR package I'll close this one.

**Comment by Mette-Jill** [comment] 2020-03-20 14:57
consider it closed!

**Closed as completed** 2020-03-20 15:06 UTC
Labels: bug, help wanted, question
